config/routes.rb
Rails.application.routes.draw do

  

  resources :continents

  resources :guides

  resources :users

  resources :itineraries do
    resources :event_votes
    resources :hints do
      resources :hint_votes
    end
  end

  resource :session

  root 'itineraries#index'

  get "/signin" => "sessions#new"
  get "/signup" => "users#new"

end

app/models/continent.rb
class Continent < ActiveRecord::Base
	# attr_accessible :continent_name, :guides_attributes
	has_many :guides, dependent: :destroy
#	accepts_nested_attributes_for :guides, allow_destroy: true

	CONT = ["Australia", "Asia-Pacific", "Europe", "Africa", "Middle East", "North America", "South America"]
end

app/models/event_vote.rb
class EventVote < ActiveRecord::Base
  belongs_to :itinerary
  belongs_to :user

end

app/models/guide.rb
class Guide < ActiveRecord::Base
	# attr_accessible :title, :intro, :continent_id, :itineraries_attributes
	has_many :itineraries, dependent: :destroy
	belongs_to :continent
	accepts_nested_attributes_for :itineraries, allow_destroy: true
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :itinerary
  has_many :hint_votes, dependent: :destroy
end

app/models/hint_vote.rb
class HintVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :hint
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
	# attr_accessible :entry, :image_url, :address, :title, :guide_id, :user_id, :hints_attributes
	belongs_to :user
	belongs_to :guide
	has_many :event_votes, dependent: :destroy
	has_many :hints, dependent: :destroy

	accepts_nested_attributes_for :hints, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :itineraries
	has_many :event_votes, dependent: :destroy
	has_many :hint_votes, dependent: :destroy
  has_secure_password
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
	before_action :load_continents
	
	def show
		@continent = Continent.find(params[:id])
	end

	def new
		@continent = Continent.new
	end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
	before_action :load_continents

	def show
		@guide = Guide.find(params[:id])
	end

	def edit
		@guide = Guide.find(params[:id])		
	end

	def update
		@guide = Guide.find(params[:id])
		if @guide.update(guide_params)
			redirect_to @guide, notice: "Successfully editted guide"
		else
			render :edit
		end
	end

private
	def guide_params
		params.require(:guide).permit(
			:title, :intro, :continent_id,
			itineraries_attributes: [:id, :guide_id, :user_id, :title, :entry, :address, :image_url,
				hints_attributes: [:id, :entry, :itinerary_id]]
			)
	end

end

app/controllers/hint_votes_controller.rb
class HintVotesController < ApplicationController
	def create
		# @itinerary = Itinerary.find(params[:itinerary_id])
		@hint = Hint.find(params[:hint_id])
		@hint.hint_votes.create!(user: current_user)
		redirect_to root_url, notice: "Thanks for voting on the hint!"
	end

	def destroy
		@hint_vote = HintVote.find(params[:id])
		@hint_vote.destroy
		redirect_to root_url, notice: "Down voted the hint!"
	end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
	def index
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hints = @itinerary.hints
	end

	def edit
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.find(params[:id])
	end

	def new
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.new
	end

	def create
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = Hint.new(hint_params)
		@hint.itinerary = @itinerary
		if @hint.save
			redirect_to itinerary_hints_path(@itinerary), notice: 'Hint created! Want to add more?'
		else
			render :new
		end
	end

	def update
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.find(params[:id])
		if @hint.update(hint_params)
			redirect_to itinerary_hints_path(@itinerary), notice: 'successfully editted hint'
		else 
			render :edit
		end
	end

private
	def hint_params
		params.require(:hint).permit(:entry)
	end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]
  before_action :require_correct_user2, only: [:edit, :update, :destroy]

  # GET /itineraries
  # GET /itineraries.json
  def index
    @itineraries = Itinerary.all
    @continents = Continent.all
  end

  # GET /itineraries/1
  # GET /itineraries/1.json
  def show
  end

  # GET /itineraries/new
  def new
    @itinerary = Itinerary.new
  end

  # GET /itineraries/1/edit
  def edit
  end

  # POST /itineraries
  # POST /itineraries.json
  def create
    @itinerary = Itinerary.new(itinerary_params)
    @itinerary.user = current_user

    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to new_itinerary_hint_path(@itinerary), notice: 'Itinerary was successfully created, now create some hints!.' }
        format.json { render :show, status: :created, location: @itinerary }
      else
        format.html { render :new }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itineraries/1
  # PATCH/PUT /itineraries/1.json
  def update
    respond_to do |format|
      if @itinerary.update(itinerary_params)
        format.html { redirect_to @itinerary, notice: 'Itinerary was successfully updated.' }
        format.json { render :show, status: :ok, location: @itinerary }
      else
        format.html { render :edit }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itineraries/1
  # DELETE /itineraries/1.json
  def destroy
    @itinerary.destroy
    respond_to do |format|
      format.html { redirect_to itineraries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      @itinerary = Itinerary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itinerary_params
      params.require(:itinerary).permit(:entry, :author, :image_url, :address, :day)
    end

    def require_correct_user2
      if current_user.id != @itinerary.user_id
        redirect_to root_path, alert: 'Please login as the correct user!'
      end    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome #{user.email}"
			redirect_to(session[:intended_url] || itineraries_path)
			session[:intended_url] = nil
		else
			flash.now[:alert] = "Invalid email/password combination"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to itineraries_path, alert: "You are now signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to itineraries_path, notice: "User successfully created!"
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		session[:user_id] = nil
		@user.destroy
		redirect_to itineraries_path, alert: "Account deleted! "
	end

private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/event_votes_helper.rb
module EventVotesHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/hint_votes_helper.rb
module HintVotesHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/itineraries/_form.html.erb
<%= form_for(@itinerary) do |f| %>
  <% if @itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% @itinerary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :vote %><br>
    <%= f.number_field :vote %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itineraries/edit.html.erb
<h1>Editing itinerary</h1>

<%= render 'form' %>


<%= link_to 'Show', @itinerary %> |
<%= link_to 'Back', itineraries_path %>

app/views/itineraries/index.html.erb
<div class="container" id="main"> 


        <!-- Itinerary Intro -->
        <div class="row" id="itineraryIntro">

            <div class="col-sm-1">

                <div class="diamondSection">
                    <a href="#">
                        <h3>Diamond Picture</h3>
                        <h3 class="diamondScore">145</h3>
                    </a>
                </div>

            </div>

            <div class="col-sm-11">
                <h1><a href="#" class="mainHeading">Hipster's 2013 Travel Guide to Sao Paulo</a></h1>
                <div class="itineraryInfo">
                    <p>Submitted time_ago_in_words(xxxxxx.created_at) ago by Username </p>
                </div>
                <p class="lead">
                    Need to add new column for interary introduction
                </p>

                <%= link_to 'Add New Itinerary', new_itinerary_path %>
            </div>
        </div>
        <!-- end Itinerary Intro -->

        <!-- ####################### START OF BLOCK -->
        <% @itineraries.each do |itinerary| %>
        <!-- Itinerary List -->
        <div class="row" id="itineraryList">

            <div class="col-sm-1" id="indent"></div>

            <div class="col-sm-11 feature">
                <div class="panel clearfix">
                    <div class="panel-heading clearfix">
                        <div class="col-sm-1">
                            <div class="itineraryScore">
                                <h4><%= itinerary.event_votes.size %></h4>
                                <!-- ###################### vote for itinerary if statement #########################-->
                                        <% if itinerary.event_votes.find_by(user: current_user) %>
                                          <%= button_to "Downvote", itinerary_event_vote_path(itinerary.id, itinerary.event_votes.find_by!(user: current_user)), method: :delete %>
                                        <% else %>
                                          <%= button_to "Upvote", itinerary_event_votes_path(itinerary)  %>
                                        <% end %>
                                <!-- ###################### end of vote for itinerary if statement  #########################-->        
                            </div>
                        </div>
                        <div class="col-sm-10">

                            <div class="itineraryTitle">                               
                                <h4 class="panel-title"><%= link_to itinerary.title, itinerary %></h4>
                                <div class="itineraryAddress">
                                    <%= itinerary.address %>
                                </div>                               
                            </div>

                        </div>
                        <div class="col-sm-1">
                            <div class="itineraryDuration">
                                <h5>4 hours (take it off??)</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="panelContent">
                            <p><%= itinerary.entry %></p>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="tipsHeader-container">
                            <p class="tipsHeader">Travel Tips <small>(<%= itinerary.hints.size %>)</small></p>
                            <%= button_to "Add your tip!", new_itinerary_hint_path(itinerary), method: :get, class: "btn btn-small pull-right addTip-button"  %>
                        </div>

                        <div class="container eachTip">
                            <div class="col-sm-12">

                                    <table>
                                        <tbody>
                                          <!-- ##################### ITINERARY HINT BLOCK START -->
                                          <% itinerary.hints.each do |hint| %>
                                            <tr>
                                                <td class="hintsTips hintsTips-first">
                                                    <h5 class="pull-left scoreTip"><%= hint.hint_votes.size %></h5>
                                                      <!-- ###################### vote for hint if statement #########################-->
                                                      <% if hint.hint_votes.find_by(user: current_user) %>
                                                        <%= button_to "DownVote", itinerary_hint_hint_vote_path(itinerary, hint, hint.hint_votes.find_by!(user: current_user)), method: :delete %>
                                                      <% else %>
                                                        <%= button_to "UpVote", itinerary_hint_hint_votes_path(itinerary, hint) %> 
                                                      <% end %>
                                                      <!-- ###################### end of vote for itinerary if statement #########################-->
                                                    <p class=""><%= hint.entry %></p>
                                                </td>
                                            </tr>
                                          <!-- ##################### ITINERARY HINT BLOCK END -->  
                                          <% end %>
                                          
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end Itinerary List --> 

        <!-- ####################### END OF BLOCK -->
              <% end %>
              
        </div><!-- end container main -->
               
        



 


<!-- 

<table>
  <thead>
    <tr>
      <th>Entry</th>
      <th>Author</th>
      <th>Image url</th>
      <th>Vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itineraries.each do |itinerary| %> 
      <tr>
        
        <td><h3><%= pluralize(itinerary.event_votes.size, "vote") %></h3></td>

        <% if itinerary.event_votes.find_by(user: current_user) %>
          <td><%= button_to "Downvote", itinerary_event_vote_path(itinerary.id, itinerary.event_votes.find_by!(user: current_user)), method: :delete %></td>
        <% else %>
          <td><%= button_to "Upvote", itinerary_event_votes_path(itinerary)  %></td>
        <% end %>

        <td><%= itinerary.address %></td>
        <td><%= itinerary.entry %></td>
        <td><%= itinerary.user.email %></td>
        <td><%= itinerary.image_url %></td>

        <td>
          <ul>
            <% itinerary.hints.each do |hint| %>
              <li><%= hint.entry %> | 
                <%= pluralize(hint.hint_votes.size, 'Hint Vote') %> | 

                <% if hint.hint_votes.find_by(user: current_user) %>
                  <%= button_to "DownVote", itinerary_hint_hint_vote_path(itinerary, hint, hint.hint_votes.find_by!(user: current_user)), method: :delete %>
                <% else %>
                  <%= button_to "UpVote", itinerary_hint_hint_votes_path(itinerary, hint) %> | 
                <% end %>
                
              </li>
            <% end %>
          </ul> 
        </td>   
        
        <td><%= link_to 'Show', itinerary %></td>
        <td><%= link_to 'Edit', edit_itinerary_path(itinerary) %></td>
        <td><%= link_to 'Destroy', itinerary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itinerary', new_itinerary_path %>


-->

app/views/itineraries/new.html.erb
<h1>New itinerary</h1>

<%= render 'form' %>

<%= link_to 'Back', itineraries_path %>

app/views/itineraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry:</strong>
  <%= @itinerary.entry %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @itinerary.image_url %>
</p>

<p>
  <strong>Address:</strong>
  <%= @itinerary.address %>
</p>

<p>
  <strong>Hint:</strong>
  <% @itinerary.hints.each do |hint| %>
 	<p>
 		<%= hint.entry %> | 
 		<%= link_to "Edit hint", edit_itinerary_hint_path(@itinerary, hint) %>
 	</p> 
  <% end %>
</p>



<%= link_to 'Edit itinerary', edit_itinerary_path(@itinerary) %> |
<%= link_to 'Back', itineraries_path %>