config/routes.rb
Rails.application.routes.draw do

  

  resources :continents

  resources :guides

  resources :users

  resources :itineraries do
    resources :event_votes
    resources :hints do
      resources :hint_votes
    end
  end

  resource :session

  root 'itineraries#index'

  get "/signin" => "sessions#new"
  get "/signup" => "users#new"

end

app/models/continent.rb
class Continent < ActiveRecord::Base
	# attr_accessible :continent_name, :guides_attributes
	has_many :guides, dependent: :destroy
#	accepts_nested_attributes_for :guides, allow_destroy: true

	CONT = ["Australia", "Asia-Pacific", "Europe", "Africa", "Middle East", "North America", "South America"]
end

app/models/event_vote.rb
class EventVote < ActiveRecord::Base
  belongs_to :itinerary
  belongs_to :user

end

app/models/guide.rb
class Guide < ActiveRecord::Base
	# attr_accessible :title, :intro, :continent_id, :itineraries_attributes
	has_many :itineraries, dependent: :destroy
	belongs_to :continent
	accepts_nested_attributes_for :itineraries, allow_destroy: true
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :itinerary
  has_many :hint_votes, dependent: :destroy
end

app/models/hint_vote.rb
class HintVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :hint
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
	# attr_accessible :entry, :image_url, :address, :title, :guide_id, :user_id, :hints_attributes
	belongs_to :user
	belongs_to :guide
	has_many :event_votes, dependent: :destroy
	has_many :hints, dependent: :destroy

	accepts_nested_attributes_for :hints, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :itineraries
	has_many :event_votes, dependent: :destroy
	has_many :hint_votes, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_signin
  	unless current_user
  		session[:intended_url] = request.url
  		redirect_to new_session_path, alert: "Please sign in first!"
  	end
  end

  def require_correct_user
  	@user = User.find(params[:id])
  	unless current_user?(@user)
  		redirect_to intineraries_path, alert: "incorrect user!"
  	end
  end

  def current_user?(user)
  	current_user == user
  end

  def load_continents
    @continents = Continent.all
  end



end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
	before_action :load_continents
	
	def show
		@continent = Continent.find(params[:id])
	end

	def new
		@continent = Continent.new
	end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
	before_action :load_continents

	def show
		@guide = Guide.find(params[:id])
	end

	def edit
		@guide = Guide.find(params[:id])		
	end

	def update
		@guide = Guide.find(params[:id])
		if @guide.update(guide_params)
			redirect_to @guide, notice: "Successfully editted guide"
		else
			render :edit
		end
	end

private
	def guide_params
		params.require(:guide).permit(
			:title, :intro, :continent_id,
			itineraries_attributes: [:id, :guide_id, :user_id, :title, :entry, :address, :image_url,
				hints_attributes: [:id, :entry, :itinerary_id]]
			)
	end

end

app/controllers/hint_votes_controller.rb
class HintVotesController < ApplicationController
	def create
		# @itinerary = Itinerary.find(params[:itinerary_id])
		@hint = Hint.find(params[:hint_id])
		@hint.hint_votes.create!(user: current_user)
		redirect_to root_url, notice: "Thanks for voting on the hint!"
	end

	def destroy
		@hint_vote = HintVote.find(params[:id])
		@hint_vote.destroy
		redirect_to root_url, notice: "Down voted the hint!"
	end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
	def index
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hints = @itinerary.hints
	end

	def edit
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.find(params[:id])
	end

	def new
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.new
	end

	def create
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = Hint.new(hint_params)
		@hint.itinerary = @itinerary
		if @hint.save
			redirect_to itinerary_hints_path(@itinerary), notice: 'Hint created! Want to add more?'
		else
			render :new
		end
	end

	def update
		@itinerary = Itinerary.find(params[:itinerary_id])
		@hint = @itinerary.hints.find(params[:id])
		if @hint.update(hint_params)
			redirect_to itinerary_hints_path(@itinerary), notice: 'successfully editted hint'
		else 
			render :edit
		end
	end

private
	def hint_params
		params.require(:hint).permit(:entry)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome #{user.email}"
			redirect_to(session[:intended_url] || itineraries_path)
			session[:intended_url] = nil
		else
			flash.now[:alert] = "Invalid email/password combination"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to itineraries_path, alert: "You are now signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to itineraries_path, notice: "User successfully created!"
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		session[:user_id] = nil
		@user.destroy
		redirect_to itineraries_path, alert: "Account deleted! "
	end

private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/event_votes_helper.rb
module EventVotesHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/hint_votes_helper.rb
module HintVotesHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/continents/new.html.erb
<%= form_for @continent do |c| %>
	<%= c.label 'What continent?' %>
	<%= c.select :continent_name, Continent::CONT, prompt: "Pick one" %> </br>
	<%= c.submit %>
<% end %>

app/views/continents/show.html.erb
<% @continent.guides.each do |guide| %>
	<ul>
		<li><h1><%= link_to guide.title, guide %></h1> </li>
		<li><%= truncate(guide.intro, length: 150)  %></li>
	</ul>
<% end %>

app/views/guides/_form.html.erb
<%= form_for(@guide) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :intro %><br>
    <%= f.text_area :intro, cols: 75, rows: 5 %>
  </div>

<%= f.fields_for :itineraries do |builder| %>
  <%= render 'itinerary_fields', f: builder %>

<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guides/_hint_fields.html.erb
<fieldset>
	<%= f.label :entry, 'Hint entry' %>
	<%= f.text_area :entry %>
</fieldset>

app/views/guides/_itinerary_fields.html.erb
   <fieldset>
    <%= f.label :title %> 
    <%= f.text_field :title %> <br/>
    <%= f.label :entry, "Entry" %> 
    <%= f.text_area :entry, cols: 100, rows: 5 %><br/>
    <%= f.label :address, "Address here:" %> 
    <%= f.text_field :address %><br/>
    <%= f.label :image_url %> 
    <%= f.text_field :image_url %> <br/>  

    <%= f.fields_for :hints do |builder| %>
        <%= render 'hint_fields', f: builder %>
    <% end %>   
  </fieldset>

app/views/guides/edit.html.erb
<h1>Editting Guide</h1>

<%= render 'form' %>

app/views/guides/show.html.erb
       <!-- Itinerary Intro -->
        <div class="row" id="itineraryIntro">

            <div class="col-sm-1">

                <div class="diamondSection">
                    <a href="#">
                        <h3>Diamond Picture</h3>
                        <h3 class="diamondScore">145</h3>
                    </a>
                </div>

            </div>

            <div class="col-sm-11">
                <h1><a href="#" class="mainHeading"><%= @guide.title %></a></h1>
                <div class="itineraryInfo">
                    <p>Submitted <%= time_ago_in_words(@guide.created_at) %> ago by Username </p>
                </div>
                <p class="lead">
                    <%= @guide.intro %>
                </p>

                <%= link_to 'Add New Itinerary', new_itinerary_path %>
            </div>
        </div>
        <!-- end Itinerary Intro -->

        <!-- ####################### START OF BLOCK -->
        <% @guide.itineraries.each do |itinerary| %>
        <!-- Itinerary List -->
        <div class="row" id="itineraryList">

            <div class="col-sm-1" id="indent"></div>

            <div class="col-sm-11 feature">
                <div class="panel clearfix">
                    <div class="panel-heading clearfix">
                        <div class="col-sm-1">
                            <div class="itineraryScore">
                                <h4><%= itinerary.event_votes.size %></h4>
                                <!-- ###################### vote for itinerary if statement #########################-->
                                        <% if itinerary.event_votes.find_by(user: current_user) %>
                                          <%= button_to "Downvote", itinerary_event_vote_path(itinerary.id, itinerary.event_votes.find_by!(user: current_user)), method: :delete %>
                                        <% else %>
                                          <%= button_to "Upvote", itinerary_event_votes_path(itinerary)  %>
                                        <% end %>
                                <!-- ###################### end of vote for itinerary if statement  #########################-->        
                            </div>
                        </div>
                        <div class="col-sm-10">

                            <div class="itineraryTitle">                               
                                <h4 class="panel-title"><%= link_to itinerary.title, itinerary %></h4>
                                <div class="itineraryAddress">
                                    <%= itinerary.address %>
                                </div>                               
                            </div>

                        </div>
                        <div class="col-sm-1">
                            <div class="itineraryDuration">
                                <h5>4 hours (take it off??)</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="panelContent">
                            <p><%= itinerary.entry %></p>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="tipsHeader-container">
                            <p class="tipsHeader">Travel Tips <small>(<%= itinerary.hints.size %>)</small></p>
                            <%= button_to "Add your tip!", new_itinerary_hint_path(itinerary), method: :get, class: "btn btn-small pull-right addTip-button"  %>
                        </div>

                        <div class="container eachTip">
                            <div class="col-sm-12">

                                    <table>
                                        <tbody>
                                          <!-- ##################### ITINERARY HINT BLOCK START -->
                                          <% itinerary.hints.each do |hint| %>
                                            <tr>
                                                <td class="hintsTips hintsTips-first">
                                                    <h5 class="pull-left scoreTip"><%= hint.hint_votes.size %></h5>
                                                      <!-- ###################### vote for hint if statement #########################-->
                                                      <% if hint.hint_votes.find_by(user: current_user) %>
                                                        <%= button_to "DownVote", itinerary_hint_hint_vote_path(itinerary, hint, hint.hint_votes.find_by!(user: current_user)), method: :delete %>
                                                      <% else %>
                                                        <%= button_to "UpVote", itinerary_hint_hint_votes_path(itinerary, hint) %> 
                                                      <% end %>
                                                      <!-- ###################### end of vote for itinerary if statement #########################-->
                                                    <p class=""><%= hint.entry %></p>
                                                </td>
                                            </tr>
                                          <!-- ##################### ITINERARY HINT BLOCK END -->  
                                          <% end %>
                                          
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end Itinerary List --> 

        <!-- ####################### END OF BLOCK -->
              <% end %>
              
        </div><!-- end container main -->
               

app/views/hints/_form.html.erb
<%= form_for [@itinerary, @hint] do |f| %>
  <% if @itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% @itinerary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hints/edit.html.erb
<h1>Edit hint!</h1>

<%= render 'form' %>

app/views/hints/index.html.erb

<% @hints.each do |hint| %>
	<ul>
		<li>
			<%= hint.entry %> |
			<%= link_to 'Edit hint', edit_itinerary_hint_path(@itinerary, hint) %>

		</li>
	</ul>
<% end %>

<%= link_to 'Add new hint!', new_itinerary_hint_path(@itinerary) %>


app/views/hints/new.html.erb
<h1>Add a hint!</h1>

<%= render 'form' %>

app/views/hints/show.html.erb
<h1>Hints show page! </h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit  %>
<% end %>